global using Application.Features.Auth.Dtos;
global using AutoMapper;
global using Domain.Entites;
global using Domain.Errors;
global using MediatR;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using Microsoft.Extensions.Caching.Hybrid;
global using OneOf;
